# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region                 = "ap-southeast-7"
  profile                = "iac-deploy"
  skip_region_validation = true

  # Note: assume_role is commented out in common_vars.hcl
  # Uncomment the block below if you need to assume a role
  # assume_role {
  #   role_arn     = "arn:aws:iam::ACCOUNT:role/ROLE-NAME"
  #   session_name = "terragrunt-session"
  # }
}
